backend/modules/invt/models/Unit.php
<?php

namespace backend\modules\invt\models;

use Yii;
use common\behaviors\TimestampBehavior;
use common\behaviors\BlameableBehavior;
use common\behaviors\DeleteBehavior;
/**
 * This is the model class for table "invt_r_unit".
 *
 * @property integer $unit_id
 * @property string $nama
 * @property string $desc
 * @property integer $deleted
 * @property string $deleted_by
 * @property string $deleted_at
 * @property string $updated_by
 * @property string $updated_at
 * @property string $created_by
 * @property string $created_at
 */
class Unit extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
   public function behaviors(){
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => DeleteBehavior::className(),
                'hardDeleteTaskName' => 'HardDeleteDB', //default
                'enableSoftDelete' => true, //default, set false jika behavior ini ingin di bypass. cth, untuk proses debugging
            ]
        ];
    }

    public static function tableName()
    {
        return 'invt_r_unit';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['desc'], 'string'],
            [['deleted'], 'integer'],
            [['deleted_at', 'updated_at', 'created_at'], 'safe'],
            [['nama'], 'string', 'max' => 100],
            [['deleted_by', 'updated_by', 'created_by'], 'string', 'max' => 32],
            ['nama','required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'unit_id' => 'Unit ID',
            'nama' => 'Nama',
            'desc' => 'Desc',
            'deleted' => 'Deleted',
            'deleted_by' => 'Deleted By',
            'deleted_at' => 'Deleted At',
            'updated_by' => 'Updated By',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
        ];
    }

    public function getUsers(){
        return $this->hasMany(User::className(), ['user_id'=>'user_id']);
    }

    public static function getNamaUnit($unit_id)
    {
        $unit = Unit::findOne($unit_id);
        if($unit!=null){
            return $unit->nama;
        }
    }

}

backend/modules/invt/controllers/UnitController.php
<?php

namespace backend\modules\invt\controllers;

use Yii;
use backend\modules\invt\models\Unit;
use backend\modules\invt\models\User;
use backend\modules\invt\models\search\UserSearch;
use backend\modules\invt\models\search\UnitSearch;
use backend\modules\invt\models\UnitCharged;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use common\components\SwitchHandler;

/**
 * UnitController implements the CRUD actions for Unit model.
 */
class UnitController extends Controller
{
    public $menuGroup = "m-unit";
    public function behaviors()
    {
        return [
            //TODO: crud controller actions are bypassed by default, set the appropriate privilege
            'privilege' => [
                 'class' => \Yii::$app->privilegeControl->getAppPrivilegeControlClass(),
                 'skipActions' => ['*'],
                ],
                
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Unit models.
     * @return mixed
     */
    public function actionUnitBrowse()
    {
        $searchModel = new UnitSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('UnitBrowse', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Unit model.
     * @param integer $id
     * @return mixed
     */
    public function actionUnitView($id)
    {
        $modelsearch = new UserSearch();
        $query = User::find()
                        ->innerJoinWith("units")
                        ->where([Unit::tableName().".unit_id"=>$id]);
        $dataProvider = $modelsearch->search(Yii::$app->request->queryParams, $query);
        return $this->render('UnitView', [
            'model' => $this->findModel($id),
            'modelsearch'=>$modelsearch,
            'dataProvider'=>$dataProvider,
        ]);
    }

    /**
     * Creates a new Unit model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionUnitAdd()
    {
        $model = new Unit();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['unit-view', 'id' => $model->unit_id]);
        } else {
            return $this->render('UnitAdd', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Unit model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUnitEdit($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['unit-view', 'id' => $model->unit_id]);
        } else {
            return $this->render('UnitEdit', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Unit model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUnitDel($id)
    {
        $model = $this->findModel($id);
        $model->softDelete();
        return $this->redirect(['unit-browse']);
    }

    public function actionManageAdmin($unit_id)
    {
        $model = $this->findModel($unit_id);

        //switch column
        if(SwitchHandler::isSwitchRequest())
        {
            if(!isset($_POST['id']) || is_null($_POST['id']) || is_null($model) ){
                return SwitchHandler::respondWithFailed();
            }
            if(SwitchHandler::isTurningOn()){
                $this->saveAdminUnit($unit_id,$_POST['id']);
            }
            else{
                 $this->deleteAdminUnit($unit_id,$_POST['id']);
            }
            return SwitchHandler::respondWithSuccess();
        }
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $_query=null);
        return $this->render('ManageAdmin',[
            'model'=>$model,
            'dataProvider'=>$dataProvider,
            'searchModel'=>$searchModel,
        ]);

    }

    protected function saveAdminUnit($unit_id,$user_id)
    {
        $modelUnitCharged = new UnitCharged();
        $modelUnitCharged->unit_id = $unit_id;
        $modelUnitCharged->user_id = $user_id;
        if($modelUnitCharged->save())
        {
            return true;
        }
        return false;
    }

    protected function deleteAdminUnit($unit_id,$user_id)
    {
        $modelUnitCharged = UnitCharged::find()
                            ->where(['user_id'=>$user_id])
                            ->andWhere(['unit_id'=>$unit_id])
                            ->one();
        $modelUnitCharged->delete();
    }

    /**
     * Finds the Unit model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Unit the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Unit::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/invt/views/unit/ManageAdmin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use backend\modules\invt\models\UnitCharged;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\admin\models\search\WorkgroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Manage Admin Unit';
$this->params['header'] = $this->title;
$this->params['breadcrumbs'][] = ['label' => 'Unit', 'url' => ['unit-browse']];
$this->params['breadcrumbs'][] = ['label' => $model->nama, 'url' => ['unit-view', 'id' => $model->unit_id]];
$this->params['breadcrumbs'][] = $this->title;
$uiHelper = \Yii::$app->uiHelper;
?>

<?=$uiHelper->renderContentSubHeader("Unit: " . $model->nama) ?>
<?=$uiHelper->renderLine() ?>
<?=$uiHelper->beginSingleRowBlock(['id' => 'manage-member']) ?>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'tableOptions' => ['class' => 'table table-condensed table-bordered'],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'username',
                'email',
                ['class' => 'common\components\SwitchColumn',
                 'header' => 'Status',
                 'flag' => function ($data) use($model){
                    $query = UnitCharged::find()
                            ->where(['unit_id'=>$model->unit_id,'user_id'=>$data->user_id])
                            ->one();
                    if(!is_null($query)){
                        return true;
                    }
                    return false;
                 },
                 'contentOptions' => ['class' => 'col-xs-1']
                ],
            ],
        ]); ?>
<?=$uiHelper->endSingleRowBlock() ?>

backend/modules/invt/views/unit/UnitAdd.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\invt\models\Unit */

$this->title = 'Tambah Unit';
$this->params['breadcrumbs'][] = ['label' => 'Unit', 'url' => ['unit-browse']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['header']= $this->title;
?>
<div class="unit-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/invt/views/unit/UnitBrowse.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use common\components\ToolsColumn;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\invt\models\search\UnitSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Unit';
$this->params['breadcrumbs'][] = $this->title;
$this->params['header']=$this->title;
?>
<div class="unit-index">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute'=>'nama',
                'label'=>'Nama Unit',
                'format'=>'raw',
                'value'=>function($model)
                {
                        return "<a href='".Url::toRoute(['/invt/unit/unit-view', 'id' => $model->unit_id])."'>".$model->nama."</a>";
                },
            ],
            [
                'attribute'=>'desc',
                'label'=>'Deskripsi Unit',
            ],
            [
            'class' => 'common\components\ToolsColumn',
            'template' => '{manage} {edit} {del}',
            'buttons'=>[
                'manage'=>function($url, $model)
                {
                    return ToolsColumn::renderCustomButton($url, $model, 'Manage Admin', 'fa fa-user');
                }
            ],
            'urlCreator' => function ($action, $model, $key, $index) {
                if($action === 'edit') {
                    return Url::to(['unit-edit','id'=>$key]);
                }elseif ($action === 'del') {
                    return Url::to(['unit-del','id'=>$key]);
                }
                elseif ($action==='manage') {
                    return Url::to(["manage-admin",'unit_id'=>$key]);
                }
                },
            ],
        ],
    ]); ?>

</div>

backend/modules/invt/views/unit/UnitEdit.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\invt\models\Unit */

$this->title = 'Edit Unit: ' . ' ' . $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Unit', 'url' => ['unit-browse']];
$this->params['breadcrumbs'][] = ['label' => $model->nama, 'url' => ['unit-view', 'id' => $model->nama]];
$this->params['breadcrumbs'][] = 'Edit';
$this->params['header']=$this->title;
?>
<div class="unit-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/invt/views/unit/UnitView.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\grid\GridView;

$uiHelper = Yii::$app->uiHelper;

/* @var $this yii\web\View */
/* @var $model backend\modules\invt\models\Unit */

$this->title = $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'unit', 'url' => ['unit-browse']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['header']=$this->title;
?>
 <div class="pull-right">
     <?=$uiHelper->renderButtonSet([
        'template' => ['admin','edit','hapus'],
        'buttons' => [
            'admin' =>['url' => Url::to(['unit/manage-admin', 'unit_id'=> $model->unit_id]), 'label' => 'Manage Admin', 'icon' => 'fa fa-user'],
            'edit' =>['url' => Url::to(['unit/unit-edit', 'id'=> $model->unit_id]), 'label' => 'Edit Unit', 'icon' => 'fa fa-pencil'],
            'hapus'=>['url' => Url::to(['unit/unit-del', 'id'=> $model->unit_id]), 'label' => 'Hapus Unit', 'icon' => 'fa fa-trash'],
        ]  
     ]) ?>
 </div> 

<?=$uiHelper->beginSingleRowBlock(['id'=>'barang-content']); ?>
    <?= DetailView::widget([
        'model' => $model,
        'options' =>[
                'class' => 'table table-condensed detail-view'
        ],
        'attributes' => [
            [
                'attribute'=>'nama',
                'label'=>'Nama Unit',
            ],            
            [
                'attribute'=>'desc',
                'label'=>'Deskripsi Unit',
            ], 
        ],
    ]) ?>

<?=$uiHelper->renderContentSubHeader("Admin Unit: " . $model->nama) ?>
<?=$uiHelper->renderLine() ?>
<?=$uiHelper->beginSingleRowBlock(['id' => 'admin-unit']) ?>
    <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $modelsearch,
            'tableOptions' => ['class' => 'table table-condensed table-bordered'],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'username',
                'email',
            ],
        ]); ?>
<?=$uiHelper->endSingleRowBlock() ?>

<?=$uiHelper->endSingleRowBlock() ?>

backend/modules/invt/views/unit/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$uiHelper = Yii::$app->uiHelper;
/* @var $this yii\web\View */
/* @var $model backend\modules\invt\models\Unit */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="unit-form">

<?php $form = ActiveForm::begin([
    'layout' => 'horizontal',
    'options' => ['enctype' => 'multipart/form-data'],
    'fieldConfig' => [
        'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
        'horizontalCssClasses' => [
            'label'=>'col-md-3',
            'offset' => 'col-md-offset-10',
            'wrapper' => 'col-md-13',
            'error' => '',
            'hint' => '',
        ],
    ],
]); ?>

    <?= $form->field($model, 'nama',[
                       'horizontalCssClasses' => ['wrapper' => 'col-sm-7',],
                       'inputOptions' => ['placeHolder'=>'Nama Unit',]
                ])->textInput(['maxlength' => true])
                ->label("Nama Unit");
    ?>

    <?= $form->field($model, 'desc',[
                        'horizontalCssClasses' => ['wrapper' => 'col-sm-7',],
                    ])->textarea(['rows' => 6]) 
                ->label("Deskripsi Unit");
    ?>

<?=$uiHelper->beginContentRow() ?>
        <?=$uiHelper->beginContentBlock(['id'=>'grid-system2',
            'width'=>10,
        ]) ?>
    <div class="form-group">
        <div class='col-sm-offset-3 col-sm-1'></div>
            <?= Html::submitButton($model->isNewRecord ? 'Tambah' : 'Edit', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
        <?=$uiHelper->endContentBlock() ?>
<?=$uiHelper->endContentRow() ?>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/invt/views/unit/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\invt\models\search\UnitSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="unit-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'unit_id') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'desc') ?>

    <?= $form->field($model, 'deleted') ?>

    <?= $form->field($model, 'deleted_by') ?>

    <?php // echo $form->field($model, 'deleted_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>